name: SauceCTL - Cypress

on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./testrunner-toolkit/cypress/
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run US tests
        if: ${{ always() }}
        run: npm run test.sauce.ex1.us

      - name: Run EU tests
      	if: ${{ always() }}
        run: npm run test.sauce.ex1.eu